FROM eclipse-temurin:21-jdk-jammy as build
WORKDIR /app

COPY .mvn/ .mvn
COPY mvnw pom.xml ./
RUN ./mvnw dependency:resolve

COPY src ./src

# Skip tests to make the build faster
RUN ./mvnw package -DskipTests -Dcheckstyle.skip=true -Dspring-javaformat.skip=true

FROM eclipse-temurin:21-jre-jammy
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
