# PostgreSQL settings
database=postgresql
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/petclinic}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:petclinic}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:petclinic}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false

# Spring Data REST
spring.data.rest.base-path=/api

# Server settings
server.port=8080
